### ISSUE TITLE
I don't have permissions to "Add repositories"

### ISSUE THREAD

**Issue by RCMariko** [rhel-labs/instruqt#170]
The "Add repositories" button is greyed out and I get this message when I mouse over it.
"You do not have the required permissions to perform this action."

**Comment by mshriver** [comment]
This depends on your users RBAC configuration in the given environment, I don't think there are any instruqt bugs or changes to address this.

The resolution of this will depend on your user, its org, and the org admins.  The issue is similar to this: (and you may find you also don't have sources RBAC granted for your production user either) https://access.redhat.com/solutions/6386521

**Comment by RCMariko** [comment]
For the lab, we'll be provider a username & password so we should use this to walk through the demo.
