### ISSUE TITLE
openscap

### ISSUE THREAD

**Issue by wkibbe** [rhel-labs/instruqt#227]

**Comment by nlager** [comment]
Ive dug into this, and it appears that the v1 oval feed's were retired in favor of v2, and the openscap defs on RHEL 8 were not updated.  This results in a 404 not found error when you attempt to run the evaluation in step 3 of the openscap lab. 

I tested this on RHEL 9, and 9 appears to already have the proper v2 URL. 

This leads to two possible fixes.  
1. the URL in the evaluation def can be manually corrected, this is not a great fix, it should instead be reported and fixed (which i intend to do regardless). 
2. we update the lab to rhel 9

since fixing the issue in 8 will likely take some time, so it seems that updating the lab to RHEL 9 is more effective from a time perspective.

**Comment by nlager** [comment]
updating to 9, means updating text.  this is a log of things that need to be changed. 

In step 2, there are several outputs that need to be re-run on 9 and updated. 

Step 3 also has output to update.

Also step 4, update the output.

**Comment by nlager** [comment]
I have already updated the commands in my local branch such that they reference the rhel 9 rules.

**Comment by nlager** [comment]
also updated the base image to 9 in my local branch.  will test the lab this afternoon, and get the output needed to update the above content blocks.

**Comment by nlager** [comment]
step 1 content should be updated.  the rhel 9 scap-security-guide only installs the file for 9. and only the -ds.xml...  the text in this step suggests there should be others.

**Comment by nlager** [comment]
text output on step 2 updated.

**Comment by nlager** [comment]
I am going to drop this block from step 1's description, as it doesn't speak the truth anymore, and i do not think it makes sense to replace it with something else. 

"There are files for every platform available in a form of XCCDF, OVAL or datastream documents. In most of use cases, you want to use the datastreams, which filenames end with *-ds.xml*. SCAP datastreams represent a bundle of profiles which are used to define a compliance policy."

**Comment by nlager** [comment]
This is complete, lab is out of maintenance.
