### ISSUE TITLE
image-mode-basics: Move "Launch bootc-image-builder" into its own step

### ISSUE THREAD

**Issue by benblasco** [rhel-labs/instruqt#518]
This step is really important, and I think it would be helpful to break it out into its own exercise for clarity. This gives the user more chance to focus on what this task is doing.  

I would also add an explanation of:
- why we mount the /output directory (to store the resulting build)
- why we mount the config.json
- how we pass the --type and --config directives
- how we pass the reference to the container we just built as a parameter

**Comment by benblasco** [comment]
Looking at config.json, why are we adding the customization of adding the "core" user to the blueprint? Is this a good practice as opposed to doing it via a kickstart or a cloud-init configuration?

**Comment by nzwulfin** [comment]
Adding users is a very platform + use case + policy driven equation, so none of them are better or worse inherently. It's probably a good idea to mention why we're doing it here (otherwise we can't log in b/c we don't have any other way to create a user on install in this lab)

I intend to move the BIB step, I'll look at making it a full step vs the focus of the deploy step. Creating the vm itself isn't a real 'focus' here so having BIB first and the main part of step 2 might get the same effect.

**Comment by nzwulfin** [comment]
Opened PR #520 to address, moved to the first step of the second challenge, and tried to make the user add clearer.
